import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="bg-gray-50 h-full w-full overflow-auto scrollbar-thin scrollbar-thumb-stone-400 scrollbar-track-slate-200"
    >
      <body className={inter.className}>{children}</body>
    </html>
  );
}
